# **MTN Cote d'Ivoire Analysis**

**Importing the Libraries to be used**

In [25]:
#Import the pandas library
#
import pandas as pd
#Import the Numpy library
import numpy as np

**Load Datasets**

In [26]:
# Load Telcom_dataset.csv data

tel_1=pd.read_csv('Telcom_dataset.csv')
tel_1.head(5)

  PRODUTC  VALUE               DATETIME  ... COUNTRY_B     CELL_ID     SITE_ID
0   Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1     sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2     sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3   Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4   Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv

[5 rows x 10 columns]

In [27]:
# Load Telcom_dataset2.csv data

tel_2=pd.read_csv('Telcom_dataset2.csv')
tel_2.head(5)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0     sms      0  2012-05-07 23:02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1   Voice      0  2012-05-07 23:03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2
2     sms      0  2012-05-07 23:04:06.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q
3   Voice     37  2012-05-07 23:04:48.0  ...     19e2e  /xvRrCVKoQ  /xvRrCVKoQ
4     sms     25  2012-05-07 23:04:58.0  ...     19e2e  +bO+qkSonO  +bO+qkSonO

[5 rows x 10 columns]

In [28]:
# Load Telcom_dataset3.csv data

tel_3=pd.read_csv('Telcom_dataset3.csv')
tel_3.head(5)

  PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B      CELLID     SIET_ID
0   Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1     sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx
2   Voice     10  2012-05-08 23:02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
3     sms      0  2012-05-08 23:03:04.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4   Voice     22  2012-05-08 23:03:16.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA

[5 rows x 10 columns]

In [71]:
# Load cells_geo.csv data

cells_geo=pd.read_csv('cells_geo.csv', delimiter=';')
cells_geo.head(5)

   Unnamed: 0   VILLES      STATUS  ... AREA     CELL_ID   SITE_CODE
0           0   ADJAME  In Service  ...  NaN  fbb2e75af3  0bb492ef17
1           1   ADJAME  In Service  ...  NaN  1502501d78  0bb492ef17
2           2   ADJAME  In Service  ...  NaN  0c2e182a0c  0bb492ef17
3           3  ASSINIE  In Service  ...  NaN  69bdfc69fd  8a1e6ce31f
4           4  ASSINIE  In Service  ...  NaN  7a1029d2ab  8a1e6ce31f

[5 rows x 12 columns]

### Telcom Datasets Cleaning

In [129]:
# correct the colunm produtc in Telcom_dataset.csv to read same as others
tel_1new=tel_1.rename(columns={'PRODUTC':'PRODUCT','DATETIME':'DATE_TIME'}, inplace=False)
tel_1new

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0      Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1        sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2        sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3      Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4      Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...      ...    ...                    ...  ...       ...         ...         ...
4996     sms    100  2012-05-07 00:01:54.0  ...     OTHER  0c2371d9bc  1e751d08a4
4997   Voice      1  2012-05-07 00:01:54.0  ...     19e2e  5fb791cf56  65efe2bc62
4998   Voice      0  2012-05-07 00:01:54.0  ...     19e2e  7773627c12  9ef9616350
4999   Voice      0  2012-05-07 00:01:54.0  ...     19e2e  3f4af49d6c  969b8d0e39
5000   Voice      7  2012-05-07 00:01:54.0  ...     19e2e  6f4d9b77a5  ebfc58af70

[5001 rows x 10 columns]

In [130]:
# correct the colunm DW_A_NUMBER to DW_A_NUMBER_INT,,DW_B_NUMBER to DW_B_NUMBER_INT in Telcom_dataset.csv to read same as others
tel_2new=tel_2.rename(columns={'DW_A_NUMBER':'DW_A_NUMBER_INT','DW_B_NUMBER':'DW_B_NUMBER_INT'}, inplace=False)
tel_2new

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0        sms      0  2012-05-07 23:02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1      Voice      0  2012-05-07 23:03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2
2        sms      0  2012-05-07 23:04:06.0  ...     19e2e  +laSrk7g6q  +laSrk7g6q
3      Voice     37  2012-05-07 23:04:48.0  ...     19e2e  /xvRrCVKoQ  /xvRrCVKoQ
4        sms     25  2012-05-07 23:04:58.0  ...     19e2e  +bO+qkSonO  +bO+qkSonO
...      ...    ...                    ...  ...       ...         ...         ...
4996     sms      0  2012-05-08 00:01:53.0  ...     19e2e  896459aace  b7d00e59e4
4997     sms     25  2012-05-08 00:01:53.0  ...     19e2e  7e90b35166  211015b14d
4998     sms      0  2012-05-08 00:01:53.0  ...     19e2e  fe70e431df  c7ea989264
4999    data      0  2012-05-08 00:01:53.0  ...     OTHER  ffa6759bb2         NaN
5000   Voice      0  2012-05-08 00:01:53.0  ...     19e2e  8630058aca  b47a998a3e

[5001 rows x 10 columns]

In [131]:
# correct the colunm CELLID, to CELL_ID,SIET_ID to SITE_ID in Telcom_dataset.csv to read same as others
tel_3new=tel_3.rename(columns={'CELLID':'CELL_ID','SIET_ID':'SITE_ID'}, inplace=False)
tel_3new

     PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0      Voice     61  2012-05-08 23:01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1        sms      0  2012-05-08 23:01:31.0  ...     19e2e  +Fs4mTvdKx  +Fs4mTvdKx
2      Voice     10  2012-05-08 23:02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
3        sms      0  2012-05-08 23:03:04.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4      Voice     22  2012-05-08 23:03:16.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA
...      ...    ...                    ...  ...       ...         ...         ...
4996   Voice      0  2012-05-09 00:01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
4997   Voice     62  2012-05-09 00:01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
4998   Voice     32  2012-05-09 00:01:43.0  ...     19e2e  a4731e780e  d68260ef50
4999   Voice     30  2012-05-09 00:01:43.0  ...     19e2e  98ed726da2  b4130b54ab
5000   Voice     60  2012-05-09 00:01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[5001 rows x 10 columns]

**Merge the three datesets of Telcom_datasets**

In [132]:
# Merge Telcom_dataset,telcom_dataset2,Telcom_dataset3
tel_123=pd.concat([tel_1new,tel_2new,tel_3new],ignore_index=True)            
tel_123

      PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0       Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1         sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2         sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3       Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4       Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...       ...    ...                    ...  ...       ...         ...         ...
14998   Voice      0  2012-05-09 00:01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
14999   Voice     62  2012-05-09 00:01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
15000   Voice     32  2012-05-09 00:01:43.0  ...     19e2e  a4731e780e  d68260ef50
15001   Voice     30  2012-05-09 00:01:43.0  ...     19e2e  98ed726da2  b4130b54ab
15002   Voice     60  2012-05-09 00:01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[15003 rows x 10 columns]

In [134]:
# Delete duplicate values
tel_123.duplicated()
tel_dup=tel_123.drop_duplicates()
tel_dup

      PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0       Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1         sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2         sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3       Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4       Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...       ...    ...                    ...  ...       ...         ...         ...
14997   Voice     10  2012-05-09 00:01:43.0  ...     OTHER  6467daa1db  8a96bae9c1
14998   Voice      0  2012-05-09 00:01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
14999   Voice     62  2012-05-09 00:01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
15001   Voice     30  2012-05-09 00:01:43.0  ...     19e2e  98ed726da2  b4130b54ab
15002   Voice     60  2012-05-09 00:01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[14750 rows x 10 columns]

In [135]:
# Delete Null data
tel_null=tel_dup.dropna()
tel_null

      PRODUCT  VALUE              DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0       Voice      0  2012-05-06 23:04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1         sms      0  2012-05-06 23:05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2         sms     25  2012-05-06 23:05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3       Voice     56  2012-05-06 23:05:42.0  ...     19e2e  +cNeJzsTp3  +cNeJzsTp3
4       Voice     14  2012-05-06 23:06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...       ...    ...                    ...  ...       ...         ...         ...
14997   Voice     10  2012-05-09 00:01:43.0  ...     OTHER  6467daa1db  8a96bae9c1
14998   Voice      0  2012-05-09 00:01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
14999   Voice     62  2012-05-09 00:01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
15001   Voice     30  2012-05-09 00:01:43.0  ...     19e2e  98ed726da2  b4130b54ab
15002   Voice     60  2012-05-09 00:01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[12789 rows x 10 columns]

In [136]:
# delect column cell_on_site,country_A,country_B in telcome_datasets
dftel=tel_null.drop(['COUNTRY_A','COUNTRY_B','CELL_ON_SITE',
              'DW_A_NUMBER_INT','DW_B_NUMBER_INT','SITE_ID'],axis=1)
dftel

      PRODUCT  VALUE              DATE_TIME     CELL_ID
0       Voice      0  2012-05-06 23:04:37.0  /TJNe+Mmtu
1         sms      0  2012-05-06 23:05:25.0  /+cKZKIp41
2         sms     25  2012-05-06 23:05:41.0  /u0FSD+ahi
3       Voice     56  2012-05-06 23:05:42.0  +cNeJzsTp3
4       Voice     14  2012-05-06 23:06:29.0  051KhYDCpv
...       ...    ...                    ...         ...
14997   Voice     10  2012-05-09 00:01:43.0  6467daa1db
14998   Voice      0  2012-05-09 00:01:43.0  2aa04dcab7
14999   Voice     62  2012-05-09 00:01:43.0  7f1f2f889f
15001   Voice     30  2012-05-09 00:01:43.0  98ed726da2
15002   Voice     60  2012-05-09 00:01:43.0  1c11a2fcbb

[12789 rows x 4 columns]

**Cell Geo Dataset Cleaning**

In [72]:
# Delete duplicate values
cells_geo.duplicated()
cells_geo1=cells_geo.drop_duplicates()
cells_geo1

      Unnamed: 0    VILLES      STATUS  ...          AREA     CELL_ID   SITE_CODE
0              0    ADJAME  In Service  ...           NaN  fbb2e75af3  0bb492ef17
1              1    ADJAME  In Service  ...           NaN  1502501d78  0bb492ef17
2              2    ADJAME  In Service  ...           NaN  0c2e182a0c  0bb492ef17
3              3   ASSINIE  In Service  ...           NaN  69bdfc69fd  8a1e6ce31f
4              4   ASSINIE  In Service  ...           NaN  7a1029d2ab  8a1e6ce31f
...          ...       ...         ...  ...           ...         ...         ...
3969        3969  ZUENOULA  In Service  ...  CENTRE NORTH  1cfc2d7ab1  f91ed8d2e9
3970        3970  ZUENOULA  In Service  ...  CENTRE NORTH  3ae1708153  f91ed8d2e9
3971        3971  ZUENOULA  In Service  ...  CENTRE NORTH  cb71f8a29c  61bee9c70c
3972        3972  ZUENOULA  In Service  ...  CENTRE NORTH  d4a6a0b645  61bee9c70c
3973        3973  ZUENOULA  In Service  ...  CENTRE NORTH  f9f3e42589  61bee9c70c

[3974 rows x 12 columns]

In [100]:
# Delete Null values
cells_geo1.isnull()
cells_geo2=cells_geo1.dropna()
cells_geo2

      Unnamed: 0    VILLES      STATUS  ...           AREA     CELL_ID   SITE_CODE
23            23     ABOBO  In Service  ...  ABIDJAN NORTH  f740406877  0f34c36ac5
24            24     ABOBO  In Service  ...  ABIDJAN NORTH  959e54c8f7  0f34c36ac5
25            25     ABOBO  In Service  ...  ABIDJAN NORTH  56b7e7000c  0f34c36ac5
26            26     ABOBO  In Service  ...  ABIDJAN NORTH  bc51c17a6f  0f34c36ac5
27            27     ABOBO  In Service  ...  ABIDJAN NORTH  e460975c9f  0f34c36ac5
...          ...       ...         ...  ...            ...         ...         ...
3969        3969  ZUENOULA  In Service  ...   CENTRE NORTH  1cfc2d7ab1  f91ed8d2e9
3970        3970  ZUENOULA  In Service  ...   CENTRE NORTH  3ae1708153  f91ed8d2e9
3971        3971  ZUENOULA  In Service  ...   CENTRE NORTH  cb71f8a29c  61bee9c70c
3972        3972  ZUENOULA  In Service  ...   CENTRE NORTH  d4a6a0b645  61bee9c70c
3973        3973  ZUENOULA  In Service  ...   CENTRE NORTH  f9f3e42589  61bee9c70c

[3880 rows x 12 columns]

In [101]:
# delete unnecesary columns
cells_geo2=cells_geo2.drop(['Unnamed: 0','AREA','LONGITUDE','LATITUDE','DECOUPZONE',
                            'ZONENAME','SITE_CODE','STATUS'],axis=1)
cells_geo2

        VILLES LOCALISATION    REGION     CELL_ID
23       ABOBO      ABIDJAN    LAGUNE  f740406877
24       ABOBO      ABIDJAN    LAGUNE  959e54c8f7
25       ABOBO      ABIDJAN    LAGUNE  56b7e7000c
26       ABOBO      ABIDJAN    LAGUNE  bc51c17a6f
27       ABOBO      ABIDJAN    LAGUNE  e460975c9f
...        ...          ...       ...         ...
3969  ZUENOULA    INTERIEUR  MARAHOUE  1cfc2d7ab1
3970  ZUENOULA    INTERIEUR  MARAHOUE  3ae1708153
3971  ZUENOULA    INTERIEUR  MARAHOUE  cb71f8a29c
3972  ZUENOULA    INTERIEUR  MARAHOUE  d4a6a0b645
3973  ZUENOULA    INTERIEUR  MARAHOUE  f9f3e42589

[3880 rows x 4 columns]

### **Merge two datasets cells_geo2 and tell_123**

In [168]:
# Merge dftel and cells_geo2 datasets
tel_cells_geo=pd.concat([dftel,cells_geo2],axis=0,ignore_index=True)            
tel_cells_geo

      PRODUCT  VALUE              DATE_TIME  ...    VILLES LOCALISATION    REGION
0       Voice    0.0  2012-05-06 23:04:37.0  ...       NaN          NaN       NaN
1         sms    0.0  2012-05-06 23:05:25.0  ...       NaN          NaN       NaN
2         sms   25.0  2012-05-06 23:05:41.0  ...       NaN          NaN       NaN
3       Voice   56.0  2012-05-06 23:05:42.0  ...       NaN          NaN       NaN
4       Voice   14.0  2012-05-06 23:06:29.0  ...       NaN          NaN       NaN
...       ...    ...                    ...  ...       ...          ...       ...
16664     NaN    NaN                    NaN  ...  ZUENOULA    INTERIEUR  MARAHOUE
16665     NaN    NaN                    NaN  ...  ZUENOULA    INTERIEUR  MARAHOUE
16666     NaN    NaN                    NaN  ...  ZUENOULA    INTERIEUR  MARAHOUE
16667     NaN    NaN                    NaN  ...  ZUENOULA    INTERIEUR  MARAHOUE
16668     NaN    NaN                    NaN  ...  ZUENOULA    INTERIEUR  MARAHOUE

[16669 rows x 7 columns]

In [176]:
# Get the most top city that use the infrastruter using 
top_cities=tel_cells_geo['VILLES'].value_counts()
top_cities.head(10)

COCODY          354
YOPOUGON        289
ABOBO           244
MARCORY         141
TREICHVILLE     132
YAMOUSSOUKRO    104
ADJAME          104
PLATEAU         100
KOUMASSI         91
BOUAKE           65
Name: VILLES, dtype: int64

In [184]:
# most used between voice,data,sms
tel_cells_geo.groupby(['PRODUCT'])[['VALUE']].sum()

            VALUE
PRODUCT
Voice    293816.0
data       2001.0
sms       52377.0

In [197]:
# find cities that are active day time
time=tel_cells_geo.groupby(['DATE_TIME'])[['VALUE']].sum()
time
time1=time.sort_values(by='VALUE', ascending=0)
time1.head(10)

                        VALUE
DATE_TIME
2012-05-09 00:00:23.0  7538.0
2012-05-08 00:00:07.0  4661.0
2012-05-08 23:51:34.0  4212.0
2012-05-08 00:00:52.0  3209.0
2012-05-09 00:00:38.0  3115.0
2012-05-07 00:00:03.0  2936.0
2012-05-08 00:00:25.0  2933.0
2012-05-07 00:01:51.0  2765.0
2012-05-09 00:01:19.0  2610.0
2012-05-07 00:01:23.0  2221.0